// Mock imagekit config BEFORE importing anything
const mockUpload = jest.fn();
const mockDeleteFile = jest.fn();
const mockGetFileDetails = jest.fn();
const mockUpdateFileDetails = jest.fn();

jest.mock("../config/imagekit.config", () => ({
  upload: mockUpload,
  deleteFile: mockDeleteFile,
  getFileDetails: mockGetFileDetails,
  updateFileDetails: mockUpdateFileDetails,
}));

const {
  uploadSingleImage,
  uploadMultipleImages,
  deleteImage,
  deleteMultipleImages,
  getImageDetails,
  updateImageDetails,
} = require("../services/imageUpload.service");
const imagekit = require("../config/imagekit.config");

describe("ImageUpload Service", () => {
  beforeEach(() => {
    jest.clearAllMocks();
  });

  describe("uploadSingleImage", () => {
    it("should upload a single image successfully", async () => {
      const mockUploadResponse = {
        url: "https://ik.imagekit.io/test/products/image.jpg",
        thumbnailUrl: "https://ik.imagekit.io/test/products/tr:n-media_library_thumbnail/image.jpg",
        fileId: "file_123",
      };

      mockUpload.mockResolvedValue(mockUploadResponse);

      const fileBuffer = Buffer.from("fake image content");
      const fileName = "test-image.jpg";

      const result = await uploadSingleImage(fileBuffer, fileName);

      expect(result).toEqual({
        url: mockUploadResponse.url,
        thumbnailUrl: mockUploadResponse.thumbnailUrl,
        id: mockUploadResponse.fileId,
      });

      expect(mockUpload).toHaveBeenCalledWith({
        file: fileBuffer,
        fileName: expect.any(String), // UUID generated by uuidv4()
        folder: "/products",
      });
    });

    it("should upload to custom folder", async () => {
      const mockUploadResponse = {
        url: "https://ik.imagekit.io/test/custom/image.jpg",
        thumbnailUrl: "https://ik.imagekit.io/test/custom/tr:n-media_library_thumbnail/image.jpg",
        fileId: "file_456",
      };

      mockUpload.mockResolvedValue(mockUploadResponse);

      const fileBuffer = Buffer.from("fake image");
      const result = await uploadSingleImage(fileBuffer, "image.jpg", "/custom");

      expect(mockUpload).toHaveBeenCalledWith(
        expect.objectContaining({
          folder: "/custom",
        })
      );
    });

    it("should throw error on upload failure", async () => {
      mockUpload.mockRejectedValue(new Error("Upload failed"));

      const fileBuffer = Buffer.from("fake image");

      await expect(uploadSingleImage(fileBuffer, "test.jpg")).rejects.toThrow(
        "Failed to upload image"
      );
    });

    it("should generate unique filename using UUID", async () => {
      const mockUploadResponse = {
        url: "https://ik.imagekit.io/test/products/image.jpg",
        thumbnailUrl: "https://ik.imagekit.io/test/products/tr:n-media_library_thumbnail/image.jpg",
        fileId: "file_789",
      };

      mockUpload.mockResolvedValue(mockUploadResponse);

      const fileBuffer = Buffer.from("fake image");
      await uploadSingleImage(fileBuffer, "original.jpg");

      const uploadCall = mockUpload.mock.calls[0][0];
      // UUID format: xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx
      expect(uploadCall.fileName).toMatch(/^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i);
    });
  });

  describe("uploadMultipleImages", () => {
    it("should upload multiple images successfully", async () => {
      const mockUploadResponse1 = {
        url: "https://ik.imagekit.io/test/products/image1.jpg",
        thumbnailUrl: "https://ik.imagekit.io/test/products/tr:n-media_library_thumbnail/image1.jpg",
        fileId: "file_1",
      };

      const mockUploadResponse2 = {
        url: "https://ik.imagekit.io/test/products/image2.jpg",
        thumbnailUrl: "https://ik.imagekit.io/test/products/tr:n-media_library_thumbnail/image2.jpg",
        fileId: "file_2",
      };

      mockUpload
        .mockResolvedValueOnce(mockUploadResponse1)
        .mockResolvedValueOnce(mockUploadResponse2);

      const files = [
        { buffer: Buffer.from("image1"), originalname: "image1.jpg" },
        { buffer: Buffer.from("image2"), originalname: "image2.jpg" },
      ];

      const result = await uploadMultipleImages(files);

      expect(result).toHaveLength(2);
      expect(result[0].id).toBe("file_1");
      expect(result[1].id).toBe("file_2");
      expect(mockUpload).toHaveBeenCalledTimes(2);
    });

    it("should return empty array when no files provided", async () => {
      const result = await uploadMultipleImages([]);
      expect(result).toEqual([]);
      expect(mockUpload).not.toHaveBeenCalled();
    });

    it("should return empty array when files is null", async () => {
      const result = await uploadMultipleImages(null);
      expect(result).toEqual([]);
      expect(mockUpload).not.toHaveBeenCalled();
    });

    it("should throw error if any upload fails", async () => {
      mockUpload
        .mockResolvedValueOnce({ url: "url1", thumbnailUrl: "thumb1", fileId: "id1" })
        .mockRejectedValueOnce(new Error("Upload failed"));

      const files = [
        { buffer: Buffer.from("image1"), originalname: "image1.jpg" },
        { buffer: Buffer.from("image2"), originalname: "image2.jpg" },
      ];

      await expect(uploadMultipleImages(files)).rejects.toThrow();
    });
  });

  describe("deleteImage", () => {
    it("should delete an image successfully", async () => {
      mockDeleteFile.mockResolvedValue({});

      await deleteImage("file_123");

      expect(mockDeleteFile).toHaveBeenCalledWith("file_123");
    });

    it("should throw error on delete failure", async () => {
      mockDeleteFile.mockRejectedValue(new Error("Delete failed"));

      await expect(deleteImage("file_123")).rejects.toThrow("Failed to delete image");
    });
  });

  describe("deleteMultipleImages", () => {
    it("should delete multiple images successfully", async () => {
      mockDeleteFile.mockResolvedValue({});

      const fileIds = ["file_1", "file_2", "file_3"];
      await deleteMultipleImages(fileIds);

      expect(mockDeleteFile).toHaveBeenCalledTimes(3);
      expect(mockDeleteFile).toHaveBeenCalledWith("file_1");
      expect(mockDeleteFile).toHaveBeenCalledWith("file_2");
      expect(mockDeleteFile).toHaveBeenCalledWith("file_3");
    });

    it("should handle empty array", async () => {
      await deleteMultipleImages([]);

      expect(mockDeleteFile).not.toHaveBeenCalled();
    });

    it("should handle null input", async () => {
      await deleteMultipleImages(null);

      expect(mockDeleteFile).not.toHaveBeenCalled();
    });

    it("should throw error if any delete fails", async () => {
      mockDeleteFile
        .mockResolvedValueOnce({})
        .mockRejectedValueOnce(new Error("Delete failed"));

      const fileIds = ["file_1", "file_2"];

      await expect(deleteMultipleImages(fileIds)).rejects.toThrow();
    });
  });

  describe("getImageDetails", () => {
    it("should get image details successfully", async () => {
      const mockDetails = {
        fileId: "file_123",
        name: "image.jpg",
        url: "https://ik.imagekit.io/test/image.jpg",
        size: 12345,
      };

      mockGetFileDetails.mockResolvedValue(mockDetails);

      const result = await getImageDetails("file_123");

      expect(result).toEqual(mockDetails);
      expect(mockGetFileDetails).toHaveBeenCalledWith("file_123");
    });

    it("should throw error on failure", async () => {
      mockGetFileDetails.mockRejectedValue(new Error("Not found"));

      await expect(getImageDetails("file_123")).rejects.toThrow(
        "Failed to get image details"
      );
    });
  });

  describe("updateImageDetails", () => {
    it("should update image details successfully", async () => {
      const mockUpdatedDetails = {
        fileId: "file_123",
        tags: ["product", "featured"],
      };

      mockUpdateFileDetails.mockResolvedValue(mockUpdatedDetails);

      const updates = { tags: ["product", "featured"] };
      const result = await updateImageDetails("file_123", updates);

      expect(result).toEqual(mockUpdatedDetails);
      expect(mockUpdateFileDetails).toHaveBeenCalledWith("file_123", updates);
    });

    it("should throw error on update failure", async () => {
      mockUpdateFileDetails.mockRejectedValue(new Error("Update failed"));

      await expect(updateImageDetails("file_123", {})).rejects.toThrow(
        "Failed to update image"
      );
    });
  });
});
